=== champix56/formation_xsl_2022-11-22/xsl/mapforce/facturationtransfert.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- W3C Schema generated by XMLSpy v2018 rel. 2 sp1 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="avgNbUnitFacture">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="refproduits" use="required" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="facturation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="statFile"/>
				<xs:element ref="factures"/>
			</xs:sequence>
			<xs:attribute name="dateTransfert" use="required" type="xs:date"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="facture">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="prixAvgArticle"/>
				<xs:element ref="ligneAvg"/>
				<xs:element ref="nbLignes"/>
			</xs:sequence>
			<xs:attribute name="idfacture" use="required" type="xs:byte"/>
			<xs:attribute name="nomClient" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="factures">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="facture" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="facturesStat">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="avgNbUnitFacture"/>
				<xs:element ref="ligneAvgFact"/>
				<xs:element ref="nbLignesFact"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ligneAvg" type="xs:decimal"/>
	<xs:element name="ligneAvgFact" type="xs:decimal"/>
	<xs:element name="nbLignes" type="xs:byte"/>
	<xs:element name="nbLignesFact" type="xs:byte"/>
	<xs:element name="prixAvgArticle">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="refproduits" use="required" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="statFile">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="facturesStat"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== champix56/formation_xsl_2022-11-22/xsl/xml/output-exemple.xml
<?xml version="1.0" encoding="UTF-8"?>
<factures xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="facturationtransfert.xsd">
	<facture idfacture="12" nomClient="123">
		<prixAvgArticle refproduits="REF-1934">8.28333333333333</prixAvgArticle>
		<ligneAvg>14.08233333333333</ligneAvg>
		<nbLignes>3</nbLignes>
	</facture>
	<facture idfacture="23" nomClient="234">
		<prixAvgArticle refproduits="REF-2234">9.95</prixAvgArticle>
		<ligneAvg>74.625</ligneAvg>
		<nbLignes>1</nbLignes>
	</facture>
	<facture idfacture="11" nomClient="234">
		<prixAvgArticle refproduits="REF-2234">9.95</prixAvgArticle>
		<ligneAvg>24.873</ligneAvg>
		<nbLignes>1</nbLignes>
	</facture>
	<facture idfacture="8" nomClient="234">
		<prixAvgArticle refproduits="REF-2234">9.95</prixAvgArticle>
		<ligneAvg>69.65</ligneAvg>
		<nbLignes>1</nbLignes>
	</facture>
	<facture idfacture="5" nomClient="132">
		<prixAvgArticle refproduits="REF-2135-2">7.61666666666667</prixAvgArticle>
		<ligneAvg>32.975</ligneAvg>
		<nbLignes>3</nbLignes>
	</facture>
</factures>
